[package]
name = "menhir-example"
version = "0.1.0"
authors = ["Naomi Testard <naomi.testard@gmail.com>"]
build = "build.rs"

[dependencies]
logos = "0.9.7"
menhir_runtime = { path = "../menhir_runtime" }

[build-dependencies]
menhir = { path = "../menhir-rs" }
